import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import { Mantine } from "@/app/providers/theme";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/dates/styles.css";
import "@/shared/lib/mobx";

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: "Заголовок",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${firaCode.className}`}>
        <Mantine>{children}</Mantine>
      </body>
    </html>
  );
}
